feat(healthcheck.go): add Ping and HealthCheck routes
kossiitkgp/KWoC-Backend pull request #113
Opened 2023-06-18 14:19 UTC by MateSousa

## Description

The Ping function responds with "pong" and returns the latency. The HealthCheck function checks the server and database status. If the database connection fails, it returns a 500 status code. If the ping to the database fails, it also returns a 500 status code. Otherwise, it returns a 200 status code and "OK".

## Related issue(s)

#111

2023-06-18 15:38 UTC, harshkhandeparkar requested changes

2023-06-18 15:38 UTC, harshkhandeparkar commented on controllers/healthcheck.go
> +	_, err = w.Write([]byte("OK"))
Can you also add a check to handle this error?

2023-06-18 15:38 UTC, harshkhandeparkar commented on server/routes.go
> +		"/api/healthcheck",
Since strict slashes are enabled, can you renamed this path to `/healthcheck/`. Also there is no need to add `/api/`

2023-06-18 15:38 UTC, harshkhandeparkar commented on server/routes.go
> +		"/api/healthcheck/ping/",
Here too, `/api/` can be removed.

2023-06-19 11:03 UTC, harshkhandeparkar commented
Thank you for the contribution! We'll merge this once #108 is merged.

2023-06-22 18:46 UTC, merged

2023-06-22 18:46 UTC, rajivharlalka commented
LGTM, Thanks a lot for the PR @MateSousa :)