[v2] Student Blog link route
kossiitkgp/KWoC-Backend pull request #131
Opened 2023-06-27 01:15 UTC by YoganshSharma

- Added `/student/bloglink/` (POST) endpoint. [Issue #126]

2023-06-27 16:09 UTC, harshkhandeparkar requested changes

2023-06-27 16:09 UTC, harshkhandeparkar commented on controllers/student_test.go
> +// Test an existing user registration request to /student/form/ with proper authentication and input
`/student/bloglink/` :)

2023-06-28 07:21 UTC, harshkhandeparkar requested changes
Some minor changes

2023-06-28 07:21 UTC, harshkhandeparkar commented on controllers/student_test.go
> +	expectStatusCodeToBe(t, res, http.StatusOK)
Can you add a response body check too?

2023-06-28 07:21 UTC, harshkhandeparkar commented on controllers/student_test.go
> +	setTestJwtSecretKey()
Please defer unset this key.

2023-06-28 09:19 UTC, YoganshSharma commented on controllers/student_test.go
> +	expectStatusCodeToBe(t, res, http.StatusOK)
done

2023-06-28 09:19 UTC, YoganshSharma commented on controllers/student_test.go
> +	setTestJwtSecretKey()
done

2023-06-28 10:10 UTC, harshkhandeparkar approved these changes

2023-06-28 12:44 UTC, rajivharlalka approved these changes
LGTM

2023-06-28 12:44 UTC, merged