#164 add_display_name #164
kossiitkgp/KWoC-Backend pull request #170
Opened 2023-12-06 10:12 UTC by ank1traj

**PR Title: Add display_name field to student and mentor models**

**PR Description:**

This PR adds a `display_name` field to student and mentor models. This field will be displayed on the website and in statistics while the `name` field will be printed on the certificate.

**Changes:**

* Add a `display_name` field to the `Student` and `Mentor` models.

**Benefits:**

* This change will make it easier for users to identify students and mentors on the website and in statistics.
* It will also make it easier to distinguish between the `display_name` and `name` fields when printing certificates.

2023-12-09 06:39 UTC, harshkhandeparkar requested changes

2023-12-09 06:39 UTC, harshkhandeparkar commented on .githooks/pre-commit
Why was this file changed?

2023-12-09 06:39 UTC, harshkhandeparkar commented on README.md
> +  - `display_name` (string): display name of the mentor
```suggestion
  - `display_name` (string): The display name of the mentor.
```

2023-12-09 06:40 UTC, harshkhandeparkar commented
Have you tested this locally?

2023-12-13 17:43 UTC, harshkhandeparkar commented
@ank1traj are you still working on this? If yes, please make the requested changes. Thanks!

2023-12-17 09:51 UTC, harshkhandeparkar commented
@ank1traj ?

2023-12-17 13:49 UTC, ank1traj commented on .githooks/pre-commit
Din't make any changes in this file. It got deleted so just added with same code.

2023-12-17 13:52 UTC, ank1traj commented
> Have you tested this locally?

Couldn't able to check due to the laptop constraints. And, sorry for missing out the above message. Didn't get the notifications before.

2023-12-17 14:02 UTC, harshkhandeparkar commented on .githooks/pre-commit
File permission seems to have changed. Can you revert this change?

2023-12-17 18:18 UTC, harshkhandeparkar commented
@ank1traj The tests were recently fixed in #179. Can you please rebase on the main branch? Thanks.

2023-12-25 10:26 UTC, harshkhandeparkar commented
@ank1traj ?

2023-12-25 10:43 UTC, closed without merging